<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="AMN"
    nsURI="http://synthesis.ipi.ac.ru/amn/" nsPrefix="amn">
  <eClassifiers xsi:type="ecore:EClass" name="Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Machine" abstract="true" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sees" upperBound="-1" eType="#//AbstractMachine"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extendsClause" upperBound="-1"
        eType="#//AbstractMachine"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sets" upperBound="-1" eType="#//SetDecl"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="promotes" upperBound="-1"
        eType="#//AMNExpression/CompoundId" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//AMNPredicate/Predicate" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invariant" upperBound="-1"
        eType="#//AMNPredicate/Predicate" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assertions" upperBound="-1"
        eType="#//AMNPredicate/Predicate" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initialization" upperBound="-1"
        eType="#//AMNSubstitution/Substitution" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operations" upperBound="-1"
        eType="#//Operation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="concreteConstants" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="concreteVariables" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractMachine" eSuperTypes="#//Machine">
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
        eType="#//AMNPredicate/Predicate" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="includes" upperBound="-1"
        eType="#//AbstractMachine"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="usesClause" upperBound="-1"
        eType="#//AbstractMachine"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstractConstants" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstractVariables" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Refinement" eSuperTypes="#//Machine">
    <eStructuralFeatures xsi:type="ecore:EReference" name="refines" eType="#//Machine"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="includes" upperBound="-1"
        eType="#//AbstractMachine"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstractConstants" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstractVariables" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Implementation" eSuperTypes="#//Machine">
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="#//AbstractMachine"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1"
        eType="#//Valuation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SetDecl" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="element" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Valuation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        eType="#//AMNExpression/Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operation" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="substitution" lowerBound="1"
        eType="#//AMNSubstitution/Substitution" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inputParams" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="outputParams" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eSubpackages name="AMNPredicate" nsURI="http://synthesis.ipi.ac.ru/amn/predicate"
      nsPrefix="amn-pred">
    <eClassifiers xsi:type="ecore:EClass" name="Predicate">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="sign" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AtomicPredicate" eSuperTypes="#//AMNPredicate/Predicate">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="2"
          upperBound="-1" eType="#//AMNExpression/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CompoundPredicate" eSuperTypes="#//AMNPredicate/Predicate">
      <eStructuralFeatures xsi:type="ecore:EReference" name="predicate" lowerBound="1"
          upperBound="-1" eType="#//AMNPredicate/Predicate" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Bracketed" eSuperTypes="#//AMNPredicate/CompoundPredicate"/>
    <eClassifiers xsi:type="ecore:EClass" name="Conjunction" eSuperTypes="#//AMNPredicate/CompoundPredicate"/>
    <eClassifiers xsi:type="ecore:EClass" name="Negation" eSuperTypes="#//AMNPredicate/CompoundPredicate"/>
    <eClassifiers xsi:type="ecore:EClass" name="Disjunction" eSuperTypes="#//AMNPredicate/CompoundPredicate"/>
    <eClassifiers xsi:type="ecore:EClass" name="Implication" eSuperTypes="#//AMNPredicate/CompoundPredicate"/>
    <eClassifiers xsi:type="ecore:EClass" name="Equivalence" eSuperTypes="#//AMNPredicate/CompoundPredicate"/>
    <eClassifiers xsi:type="ecore:EClass" name="UniversalPredicate" eSuperTypes="#//AMNPredicate/CompoundPredicate">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="variable" lowerBound="1"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ExistentialPredicate" eSuperTypes="#//AMNPredicate/CompoundPredicate">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="variable" lowerBound="1"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="AMNExpression" nsURI="http://synthesis.ipi.ac.ru/amn/expression"
      nsPrefix="amn-exp">
    <eClassifiers xsi:type="ecore:EClass" name="Expression"/>
    <eClassifiers xsi:type="ecore:EClass" name="BracketedExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
          eType="#//AMNExpression/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SetComprehension" eSuperTypes="#//AMNExpression/Expression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="variable" lowerBound="1"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="predicate" lowerBound="1"
          upperBound="-1" eType="#//AMNPredicate/Predicate" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OperationalExpression" abstract="true"
        eSuperTypes="#//AMNExpression/Expression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="sign" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UnaryOperator" eSuperTypes="#//AMNExpression/OperationalExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
          eType="#//AMNExpression/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BinaryOperator" eSuperTypes="#//AMNExpression/OperationalExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="2"
          upperBound="2" eType="#//AMNExpression/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FunctionalExpression" eSuperTypes="#//AMNExpression/OperationalExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" upperBound="-1"
          eType="#//AMNExpression/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Variable" eSuperTypes="#//AMNExpression/Expression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CompoundId" eSuperTypes="#//AMNExpression/Expression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BooleanValue" eSuperTypes="#//AMNExpression/Expression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StringValue" eSuperTypes="#//AMNExpression/Expression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IntegerValue" eSuperTypes="#//AMNExpression/Expression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SetValue" eSuperTypes="#//AMNExpression/Expression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" upperBound="-1"
          eType="#//AMNExpression/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NamedConstant" eSuperTypes="#//AMNExpression/Expression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="AMNSubstitution" nsURI="http://synthesis.ipi.ac.ru/amn/substitution"
      nsPrefix="amn-subst">
    <eClassifiers xsi:type="ecore:EClass" name="Substitution"/>
    <eClassifiers xsi:type="ecore:EClass" name="Identity" eSuperTypes="#//AMNSubstitution/Substitution"/>
    <eClassifiers xsi:type="ecore:EClass" name="Block" eSuperTypes="#//AMNSubstitution/Substitution">
      <eStructuralFeatures xsi:type="ecore:EReference" name="substitution" lowerBound="1"
          eType="#//AMNSubstitution/Substitution" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BecomesEqual" eSuperTypes="#//AMNSubstitution/Substitution">
      <eStructuralFeatures xsi:type="ecore:EReference" name="leftExpression" lowerBound="1"
          upperBound="-1" eType="#//AMNExpression/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rightExpression" lowerBound="1"
          upperBound="-1" eType="#//AMNExpression/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Precondition" eSuperTypes="#//AMNSubstitution/Substitution">
      <eStructuralFeatures xsi:type="ecore:EReference" name="pre" lowerBound="1" upperBound="-1"
          eType="#//AMNPredicate/Predicate" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="thenPart" lowerBound="1"
          eType="#//AMNSubstitution/Substitution" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Assertion" eSuperTypes="#//AMNSubstitution/Substitution">
      <eStructuralFeatures xsi:type="ecore:EReference" name="predicate" lowerBound="1"
          upperBound="-1" eType="#//AMNPredicate/Predicate" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="substitution" lowerBound="1"
          eType="#//AMNSubstitution/Substitution"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LimitedChoice" eSuperTypes="#//AMNSubstitution/Substitution">
      <eStructuralFeatures xsi:type="ecore:EReference" name="substitution" lowerBound="1"
          upperBound="-1" eType="#//AMNSubstitution/Substitution" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IfSubstitution" eSuperTypes="#//AMNSubstitution/Substitution">
      <eStructuralFeatures xsi:type="ecore:EReference" name="if" lowerBound="1" upperBound="-1"
          eType="#//AMNPredicate/Predicate" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="then" lowerBound="1"
          upperBound="-1" eType="#//AMNSubstitution/Substitution" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="else" eType="#//AMNSubstitution/Substitution"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Select" eSuperTypes="#//AMNSubstitution/Substitution">
      <eStructuralFeatures xsi:type="ecore:EReference" name="select" lowerBound="1"
          upperBound="-1" eType="#//AMNPredicate/Predicate" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="when" lowerBound="1"
          upperBound="-1" eType="#//AMNSubstitution/Substitution" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="else" eType="#//AMNSubstitution/Substitution"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Case" eSuperTypes="#//AMNSubstitution/Substitution">
      <eStructuralFeatures xsi:type="ecore:EReference" name="case" lowerBound="1"
          eType="#//AMNExpression/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="or" lowerBound="1" upperBound="-1"
          eType="#//AMNExpression/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="then" lowerBound="1"
          upperBound="-1" eType="#//AMNSubstitution/Substitution" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="else" eType="#//AMNSubstitution/Substitution"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Any" eSuperTypes="#//AMNSubstitution/Substitution">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="any" lowerBound="1" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="where" lowerBound="1"
          upperBound="-1" eType="#//AMNPredicate/Predicate" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="thenPart" lowerBound="1"
          eType="#//AMNSubstitution/Substitution" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Let" eSuperTypes="#//AMNSubstitution/Substitution">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="variable" lowerBound="1"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="be" lowerBound="1" upperBound="-1"
          eType="#//AMNPredicate/Predicate" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="in" lowerBound="1" eType="#//AMNSubstitution/Substitution"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BecomesElement" eSuperTypes="#//AMNSubstitution/Substitution">
      <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
          upperBound="-1" eType="#//AMNExpression/CompoundId" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
          eType="#//AMNExpression/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BecomesSuchThat" eSuperTypes="#//AMNSubstitution/Substitution">
      <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
          upperBound="-1" eType="#//AMNExpression/CompoundId" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="predicate" lowerBound="1"
          eType="#//AMNPredicate/Predicate" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Var" eSuperTypes="#//AMNSubstitution/Substitution">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="variable" lowerBound="1"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="substitution" lowerBound="1"
          eType="#//AMNSubstitution/Substitution" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SequenceSubstitution" eSuperTypes="#//AMNSubstitution/Substitution">
      <eStructuralFeatures xsi:type="ecore:EReference" name="substitution" lowerBound="2"
          upperBound="-1" eType="#//AMNSubstitution/Substitution" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Call" eSuperTypes="#//AMNSubstitution/Substitution">
      <eStructuralFeatures xsi:type="ecore:EReference" name="output" upperBound="-1"
          eType="#//AMNExpression/CompoundId" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="operationName" lowerBound="1"
          eType="#//AMNExpression/CompoundId" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="actualParam" upperBound="-1"
          eType="#//AMNExpression/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="While" eSuperTypes="#//AMNSubstitution/Substitution">
      <eStructuralFeatures xsi:type="ecore:EReference" name="while" lowerBound="1"
          upperBound="-1" eType="#//AMNPredicate/Predicate" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="do" lowerBound="1" eType="#//AMNSubstitution/Substitution"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="invariant" lowerBound="1"
          upperBound="-1" eType="#//AMNPredicate/Predicate" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="variant" lowerBound="1"
          eType="#//AMNExpression/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Simultaneous" eSuperTypes="#//AMNSubstitution/Substitution">
      <eStructuralFeatures xsi:type="ecore:EReference" name="substitution" lowerBound="2"
          upperBound="-1" eType="#//AMNSubstitution/Substitution" containment="true"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
